### ISSUE TITLE
Bug-user/register-yateesh-chandra-ece

### ISSUE THREAD

**Issue by KumariQA** [Event-Coordination-Engine/yateesh-chandra-ece#33]

**Comment by KumariLadi** [comment]
![Image](https://github.com/user-attachments/assets/9ae5fb1f-200b-4f4c-9371-909dcbc71b3c)

**Comment by KumariLadi** [comment]
Email should be of valid format.

**Comment by yateesh-chandra-duggirala** [comment]
This is worked as a part of feature - #32 

Solution : If the user enters invalid email, He will not get the registration mail
